### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F09-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F09-4/main#258]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline set [your deadline: 2019-11-14] (:exclamation:)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @jwyf for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-4/main/pull/250 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/244 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/238 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/222 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/202 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/151 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/250 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/244 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/238 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/222 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/198 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/197 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/196 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/194 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/193 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/190 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/189 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/183 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/179 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/177 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/172 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/171 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/169 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/168 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/167 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/166 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/165 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/164 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/157 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/156 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/155 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/154 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/153 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/111 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/86 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @rishi12438 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-4/main/issues/193 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/192 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/181 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/161 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/159 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/111 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/86 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/84 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @rohan-av for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-4/main/pull/150 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/207 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/193 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/183 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/163 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/154 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/111 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @salonethegreat for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-4/main/pull/256 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/239 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/193 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/175 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/162 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/85 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @samuel787 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F09-4/main/pull/226 https://github.com/AY1920S1-CS2113T-F09-4/main/pull/203 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/193 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/187 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/186 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/182 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/180 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/173 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/160 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/158 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/111 https://github.com/AY1920S1-CS2113T-F09-4/main/issues/86 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @langyanbin0314

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
